### ISSUE TITLE
Display location information

### ISSUE THREAD

**Issue by xofbd** [xofbd/wqu_project_s202009#1]
Let's go ahead and display the location along with the temperature. That way, visitors know where the weather data is coming from.

**Comment by turbatuandrei** [comment]
I created 2 commits on my local
![image](https://user-images.githubusercontent.com/62556955/99902253-0ccef000-2cc5-11eb-9f7d-9fc551634a27.png)

![image](https://user-images.githubusercontent.com/62556955/99902255-1193a400-2cc5-11eb-801f-2892b6b65473.png)
And now I'm trying to push them to origin
![image](https://user-images.githubusercontent.com/62556955/99902243-02acf180-2cc5-11eb-8138-a98e7a045314.png)
And I'm getting the above message.
@xofbd Could you hint me to the right direction?

**Comment by xofbd** [comment]
The first thing you'll have to do is fork the repo. When you visit the repo, look for a button that says "fork". What that'll do is create a version of the repo (a fork) on _your_ account. Since you have permission on this new version of fork, you can commit to it. Then, you'll open up a PR against to this version, asking for the changes made to your fork to be introduced to this version. Let me know if you have any follow ups.

This may help: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by turbatuandrei** [comment]
@xofbd 

I was unable to add you as a reviewer in the pullrequest, fields were not editable.

![image](https://user-images.githubusercontent.com/62556955/99916640-fa2fd780-2d13-11eb-93ec-046535723878.png)

**Comment by xofbd** [comment]
addressed by #11
