### ISSUE TITLE
Update Python version

### ISSUE THREAD

**Issue by xofbd** [xofbd/wqu_project_s202009#10]
we should update the version of Python we use in both the Docker deploy and `runtime.txt`

**Comment by turbatuandrei** [comment]
@xofbd  Can I tackle this issue next?

**Comment by xofbd** [comment]
@turbatuandrei I just assigned it to you.

**Comment by turbatuandrei** [comment]
https://github.com/xofbd/wqu_project_s202009/pull/23

**Comment by xofbd** [comment]
taken care of with PR #23
