### ISSUE TITLE
Specify package versions

### ISSUE THREAD

**Issue by xofbd** [xofbd/wqu_project_s202009#6]
We should make sure that our application is reproducible and the build is more deterministic. In other words, we specify/pin the package versions, at least the packages we use directly. This would involve modifying `requirements.txt`. Using `pip freeze` would help to realize what versions we are currently using.

**Comment by turbatuandrei** [comment]
@xofbd 
:) can I have this one also?

**Comment by xofbd** [comment]
@turbatuandrei Yes, you may. I was thinking that it should only include the packages we use directly. That can be the first step, followed by using something like pip-tools to specify the direct packages but also the versions of the sub-dependencies

**Comment by turbatuandrei** [comment]
For the packages we use directly it should look like:
![image](https://user-images.githubusercontent.com/62556955/102413157-2ed63c80-3ffd-11eb-929f-7b73df8e625e.png)
And for pip-tools should I open a new issue and look at something like:
https://alysivji.github.io/python-managing-dependencies-with-pip-tools.html
for sub-dependencies?

**Comment by turbatuandrei** [comment]
@xofbd 

I installed pip-tools, used the packages above as the .in for pip-compile and ended up with a requirements.txt that looks like:

![image](https://user-images.githubusercontent.com/62556955/102624703-0cebcf80-414d-11eb-86a0-41099d7a3281.png)


Is this the end result I should have been looking for?

**Comment by xofbd** [comment]
This was resolved with PR #25
