### ISSUE TITLE
Include USER-AGENT in header

### ISSUE THREAD

**Issue by xofbd** [xofbd/wqu_project_s202009#7]
We are using unauthenticate web APIs which are great as they are easy to get going but we may run the risk being banned due to high number of requests. One way to perhaps not be banned (or not as quickly) is to specify a USER AGENT in the request header. See lines such as https://github.com/xofbd/wqu_project_s202009/blob/db8d8b4715bb0ffe2228e5499638f89f57f91a20/wqu_app/message.py#L13

In calling `request.get`, we can pass a dictionary of key-value pairs to be used in the construction of a header. Our user agent can just be simply "wqu-project" or something similar.

**Comment by xofbd** [comment]
Several people pointed out how the application returned an Internal server issues and someone indicated the problem was from the weather API. I made a quick fix but we really should fix this on a wider level. Perhaps have a global with the header information that all calls to `requests.get` uses.

**Comment by turbatuandrei** [comment]
@xofbd Can you assign this issue to me? Thank you!

**Comment by xofbd** [comment]
@turbatuandrei You've been assigned. Make sure to pull in the latest changes before embarking on this.
