### ISSUE TITLE
Weather Forecast

### ISSUE THREAD

**Issue by xofbd** [xofbd/wqu_project_s202009#8]
Since we are getting temperature data throughout the day rather than the current temperature we may want to create a plot of the forecast of the day.

**Comment by turbatuandrei** [comment]
@xofbd  after you review https://github.com/xofbd/wqu_project_s202009/issues/1, I would like to start working on this issue, could  you assign it to me?

**Comment by xofbd** [comment]
@turbatuandrei Yes, I'll assign you this issue and you can start working on it.

You may want to consider the Python packages Altair or Bokeh for this.

**Comment by xofbd** [comment]
closed with #19
